// <auto-generated />
using System;
using LibraryAppWebAPI.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAppWebAPI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250206100346_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAppWebAPI.Base.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<bool>("CanManipulate")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalAvailableCopies")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Title");

                    b.HasDiscriminator().HasValue("Title");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanManipulate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Smith",
                            PersonalId = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1985, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            LastName = "Johnson",
                            PersonalId = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1978, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            LastName = "Williams",
                            PersonalId = "456123789"
                        },
                        new
                        {
                            Id = 4,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1995, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            LastName = "Brown",
                            PersonalId = "852963741"
                        },
                        new
                        {
                            Id = 5,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1982, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            LastName = "Jones",
                            PersonalId = "159753486"
                        },
                        new
                        {
                            Id = 6,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(2000, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            LastName = "Garcia",
                            PersonalId = "753159846"
                        },
                        new
                        {
                            Id = 7,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1998, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            LastName = "Martinez",
                            PersonalId = "951357486"
                        },
                        new
                        {
                            Id = 8,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1993, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            LastName = "Hernandez",
                            PersonalId = "789654123"
                        },
                        new
                        {
                            Id = 9,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1975, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christopher",
                            LastName = "Lopez",
                            PersonalId = "321654987"
                        },
                        new
                        {
                            Id = 10,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(2001, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            LastName = "Gonzalez",
                            PersonalId = "147258369"
                        },
                        new
                        {
                            Id = 11,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1988, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            LastName = "Perez",
                            PersonalId = "963852741"
                        },
                        new
                        {
                            Id = 12,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1992, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ava",
                            LastName = "Wilson",
                            PersonalId = "456789123"
                        },
                        new
                        {
                            Id = 13,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1980, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Matthew",
                            LastName = "Anderson",
                            PersonalId = "258147369"
                        },
                        new
                        {
                            Id = 14,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1999, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Isabella",
                            LastName = "Thomas",
                            PersonalId = "741852963"
                        },
                        new
                        {
                            Id = 15,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1983, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ethan",
                            LastName = "Taylor",
                            PersonalId = "369147258"
                        },
                        new
                        {
                            Id = 16,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(2002, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mia",
                            LastName = "Moore",
                            PersonalId = "654987321"
                        },
                        new
                        {
                            Id = 17,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1977, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alexander",
                            LastName = "White",
                            PersonalId = "987321654"
                        },
                        new
                        {
                            Id = 18,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1994, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charlotte",
                            LastName = "Harris",
                            PersonalId = "123789456"
                        },
                        new
                        {
                            Id = 19,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(1989, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liam",
                            LastName = "Clark",
                            PersonalId = "951753852"
                        },
                        new
                        {
                            Id = 20,
                            CanManipulate = false,
                            DateOfBirth = new DateTime(2003, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amelia",
                            LastName = "Lewis",
                            PersonalId = "789321654"
                        });
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MessageContext")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MessageSubject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SendData")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.QueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TitleId");

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.RentalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("MaxReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimesProlongued")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<int>("TitleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TitleId");

                    b.ToTable("RentalEntries");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Book", b =>
                {
                    b.HasBaseType("LibraryAppWebAPI.Base.Title");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.K. Rowling",
                            AvailableCopies = 12,
                            CanManipulate = false,
                            Name = "Harry Potter and the Philosopher's Stone",
                            TotalAvailableCopies = 12,
                            ISBN = "9780747532699",
                            NumberOfPages = 223
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            AvailableCopies = 8,
                            CanManipulate = false,
                            Name = "1984",
                            TotalAvailableCopies = 8,
                            ISBN = "9780451524935",
                            NumberOfPages = 328
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R. Tolkien",
                            AvailableCopies = 5,
                            CanManipulate = false,
                            Name = "The Lord of the Rings",
                            TotalAvailableCopies = 5,
                            ISBN = "9780544003415",
                            NumberOfPages = 1178
                        },
                        new
                        {
                            Id = 4,
                            Author = "F. Scott Fitzgerald",
                            AvailableCopies = 7,
                            CanManipulate = false,
                            Name = "The Great Gatsby",
                            TotalAvailableCopies = 7,
                            ISBN = "9780743273565",
                            NumberOfPages = 180
                        },
                        new
                        {
                            Id = 5,
                            Author = "Harper Lee",
                            AvailableCopies = 10,
                            CanManipulate = false,
                            Name = "To Kill a Mockingbird",
                            TotalAvailableCopies = 10,
                            ISBN = "9780061120084",
                            NumberOfPages = 281
                        },
                        new
                        {
                            Id = 6,
                            Author = "Jane Austen",
                            AvailableCopies = 6,
                            CanManipulate = false,
                            Name = "Pride and Prejudice",
                            TotalAvailableCopies = 6,
                            ISBN = "9781503290563",
                            NumberOfPages = 279
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mark Twain",
                            AvailableCopies = 9,
                            CanManipulate = false,
                            Name = "Adventures of Huckleberry Finn",
                            TotalAvailableCopies = 9,
                            ISBN = "9780486280615",
                            NumberOfPages = 366
                        },
                        new
                        {
                            Id = 8,
                            Author = "Mary Shelley",
                            AvailableCopies = 4,
                            CanManipulate = false,
                            Name = "Frankenstein",
                            TotalAvailableCopies = 4,
                            ISBN = "9780486282114",
                            NumberOfPages = 280
                        },
                        new
                        {
                            Id = 9,
                            Author = "Charlotte Brontë",
                            AvailableCopies = 5,
                            CanManipulate = false,
                            Name = "Jane Eyre",
                            TotalAvailableCopies = 5,
                            ISBN = "9780141441146",
                            NumberOfPages = 500
                        },
                        new
                        {
                            Id = 10,
                            Author = "Herman Melville",
                            AvailableCopies = 3,
                            CanManipulate = false,
                            Name = "Moby-Dick",
                            TotalAvailableCopies = 3,
                            ISBN = "9781503280786",
                            NumberOfPages = 635
                        },
                        new
                        {
                            Id = 11,
                            Author = "Leo Tolstoy",
                            AvailableCopies = 2,
                            CanManipulate = false,
                            Name = "War and Peace",
                            TotalAvailableCopies = 2,
                            ISBN = "9780198800545",
                            NumberOfPages = 1225
                        },
                        new
                        {
                            Id = 12,
                            Author = "Gabriel García Márquez",
                            AvailableCopies = 6,
                            CanManipulate = false,
                            Name = "One Hundred Years of Solitude",
                            TotalAvailableCopies = 6,
                            ISBN = "9780060883287",
                            NumberOfPages = 417
                        },
                        new
                        {
                            Id = 13,
                            Author = "Ernest Hemingway",
                            AvailableCopies = 8,
                            CanManipulate = false,
                            Name = "The Old Man and the Sea",
                            TotalAvailableCopies = 8,
                            ISBN = "9780684801223",
                            NumberOfPages = 127
                        },
                        new
                        {
                            Id = 14,
                            Author = "William Shakespeare",
                            AvailableCopies = 10,
                            CanManipulate = false,
                            Name = "Hamlet",
                            TotalAvailableCopies = 10,
                            ISBN = "9780140714548",
                            NumberOfPages = 342
                        },
                        new
                        {
                            Id = 15,
                            Author = "Oscar Wilde",
                            AvailableCopies = 7,
                            CanManipulate = false,
                            Name = "The Picture of Dorian Gray",
                            TotalAvailableCopies = 7,
                            ISBN = "9780141439570",
                            NumberOfPages = 254
                        },
                        new
                        {
                            Id = 16,
                            Author = "George R.R. Martin",
                            AvailableCopies = 5,
                            CanManipulate = false,
                            Name = "A Game of Thrones",
                            TotalAvailableCopies = 5,
                            ISBN = "9780553593716",
                            NumberOfPages = 835
                        },
                        new
                        {
                            Id = 17,
                            Author = "Aldous Huxley",
                            AvailableCopies = 6,
                            CanManipulate = false,
                            Name = "Brave New World",
                            TotalAvailableCopies = 6,
                            ISBN = "9780060850524",
                            NumberOfPages = 288
                        },
                        new
                        {
                            Id = 18,
                            Author = "Kurt Vonnegut",
                            AvailableCopies = 9,
                            CanManipulate = false,
                            Name = "Slaughterhouse-Five",
                            TotalAvailableCopies = 9,
                            ISBN = "9780440180296",
                            NumberOfPages = 275
                        },
                        new
                        {
                            Id = 19,
                            Author = "Emily Brontë",
                            AvailableCopies = 4,
                            CanManipulate = false,
                            Name = "Wuthering Heights",
                            TotalAvailableCopies = 4,
                            ISBN = "9780141439556",
                            NumberOfPages = 416
                        },
                        new
                        {
                            Id = 20,
                            Author = "J.D. Salinger",
                            AvailableCopies = 8,
                            CanManipulate = false,
                            Name = "The Catcher in the Rye",
                            TotalAvailableCopies = 8,
                            ISBN = "9780316769488",
                            NumberOfPages = 214
                        });
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Dvd", b =>
                {
                    b.HasBaseType("LibraryAppWebAPI.Base.Title");

                    b.Property<int>("NumberOfMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Dvd");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            Author = "Christopher Nolan",
                            AvailableCopies = 7,
                            CanManipulate = false,
                            Name = "Inception",
                            TotalAvailableCopies = 7,
                            NumberOfMinutes = 148,
                            PublishYear = 2010
                        },
                        new
                        {
                            Id = 22,
                            Author = "Steven Spielberg",
                            AvailableCopies = 5,
                            CanManipulate = false,
                            Name = "Jurassic Park",
                            TotalAvailableCopies = 5,
                            NumberOfMinutes = 127,
                            PublishYear = 1993
                        },
                        new
                        {
                            Id = 23,
                            Author = "Peter Jackson",
                            AvailableCopies = 8,
                            CanManipulate = false,
                            Name = "The Lord of the Rings: The Fellowship of the Ring",
                            TotalAvailableCopies = 8,
                            NumberOfMinutes = 178,
                            PublishYear = 2001
                        },
                        new
                        {
                            Id = 24,
                            Author = "Quentin Tarantino",
                            AvailableCopies = 6,
                            CanManipulate = false,
                            Name = "Pulp Fiction",
                            TotalAvailableCopies = 6,
                            NumberOfMinutes = 154,
                            PublishYear = 1994
                        },
                        new
                        {
                            Id = 25,
                            Author = "James Cameron",
                            AvailableCopies = 10,
                            CanManipulate = false,
                            Name = "Titanic",
                            TotalAvailableCopies = 10,
                            NumberOfMinutes = 195,
                            PublishYear = 1997
                        },
                        new
                        {
                            Id = 26,
                            Author = "Ridley Scott",
                            AvailableCopies = 4,
                            CanManipulate = false,
                            Name = "Gladiator",
                            TotalAvailableCopies = 4,
                            NumberOfMinutes = 155,
                            PublishYear = 2000
                        },
                        new
                        {
                            Id = 27,
                            Author = "Francis Ford Coppola",
                            AvailableCopies = 6,
                            CanManipulate = false,
                            Name = "The Godfather",
                            TotalAvailableCopies = 6,
                            NumberOfMinutes = 175,
                            PublishYear = 1972
                        },
                        new
                        {
                            Id = 28,
                            Author = "Martin Scorsese",
                            AvailableCopies = 5,
                            CanManipulate = false,
                            Name = "The Wolf of Wall Street",
                            TotalAvailableCopies = 5,
                            NumberOfMinutes = 180,
                            PublishYear = 2013
                        },
                        new
                        {
                            Id = 29,
                            Author = "Robert Zemeckis",
                            AvailableCopies = 9,
                            CanManipulate = false,
                            Name = "Forrest Gump",
                            TotalAvailableCopies = 9,
                            NumberOfMinutes = 142,
                            PublishYear = 1994
                        },
                        new
                        {
                            Id = 30,
                            Author = "Stanley Kubrick",
                            AvailableCopies = 10,
                            CanManipulate = false,
                            Name = "The Shining",
                            TotalAvailableCopies = 10,
                            NumberOfMinutes = 146,
                            PublishYear = 1980
                        },
                        new
                        {
                            Id = 31,
                            Author = "George Lucas",
                            AvailableCopies = 8,
                            CanManipulate = false,
                            Name = "Star Wars: Episode IV - A New Hope",
                            TotalAvailableCopies = 8,
                            NumberOfMinutes = 121,
                            PublishYear = 1977
                        },
                        new
                        {
                            Id = 32,
                            Author = "Christopher Nolan",
                            AvailableCopies = 6,
                            CanManipulate = false,
                            Name = "The Dark Knight",
                            TotalAvailableCopies = 6,
                            NumberOfMinutes = 152,
                            PublishYear = 2008
                        },
                        new
                        {
                            Id = 33,
                            Author = "David Fincher",
                            AvailableCopies = 5,
                            CanManipulate = false,
                            Name = "Fight Club",
                            TotalAvailableCopies = 5,
                            NumberOfMinutes = 139,
                            PublishYear = 1999
                        },
                        new
                        {
                            Id = 34,
                            Author = "Alfonso Cuarón",
                            AvailableCopies = 7,
                            CanManipulate = false,
                            Name = "Gravity",
                            TotalAvailableCopies = 7,
                            NumberOfMinutes = 91,
                            PublishYear = 2013
                        },
                        new
                        {
                            Id = 35,
                            Author = "Guillermo del Toro",
                            AvailableCopies = 4,
                            CanManipulate = false,
                            Name = "Pan's Labyrinth",
                            TotalAvailableCopies = 4,
                            NumberOfMinutes = 118,
                            PublishYear = 2006
                        },
                        new
                        {
                            Id = 36,
                            Author = "Baz Luhrmann",
                            AvailableCopies = 6,
                            CanManipulate = false,
                            Name = "The Great Gatsby",
                            TotalAvailableCopies = 6,
                            NumberOfMinutes = 143,
                            PublishYear = 2013
                        },
                        new
                        {
                            Id = 37,
                            Author = "Jon Favreau",
                            AvailableCopies = 8,
                            CanManipulate = false,
                            Name = "Iron Man",
                            TotalAvailableCopies = 8,
                            NumberOfMinutes = 126,
                            PublishYear = 2008
                        },
                        new
                        {
                            Id = 38,
                            Author = "James Cameron",
                            AvailableCopies = 5,
                            CanManipulate = false,
                            Name = "Avatar",
                            TotalAvailableCopies = 5,
                            NumberOfMinutes = 162,
                            PublishYear = 2009
                        },
                        new
                        {
                            Id = 39,
                            Author = "Frank Darabont",
                            AvailableCopies = 10,
                            CanManipulate = false,
                            Name = "The Shawshank Redemption",
                            TotalAvailableCopies = 10,
                            NumberOfMinutes = 142,
                            PublishYear = 1994
                        },
                        new
                        {
                            Id = 40,
                            Author = "Damien Chazelle",
                            AvailableCopies = 6,
                            CanManipulate = false,
                            Name = "La La Land",
                            TotalAvailableCopies = 6,
                            NumberOfMinutes = 128,
                            PublishYear = 2016
                        });
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Message", b =>
                {
                    b.HasOne("LibraryAppWebAPI.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.QueueItem", b =>
                {
                    b.HasOne("LibraryAppWebAPI.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAppWebAPI.Base.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.RentalEntry", b =>
                {
                    b.HasOne("LibraryAppWebAPI.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAppWebAPI.Base.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Title");
                });
#pragma warning restore 612, 618
        }
    }
}
